# To add a new library:
# 1. Add the dependency here but use _ as the version
# 2. Add the dependency to a module
# 3. Run ./gradlew refreshVersions
# 4. This command should add your new dependency to versions.properties
# 5. Make sure it is using the version you want

[plugins]
ksp = { id = "com.google.devtools.ksp", version = "1.8.22-1.0.11" }

[libraries]
androidGradle = "com.android.tools.build:gradle:_"
anvilGradle = "com.squareup.anvil:gradle-plugin:_"
autoValue = "com.google.auto.value:auto-value:_"
autoValueAnnotations = "com.google.auto.value:auto-value-annotations:_"
dagger = "com.google.dagger:dagger:_"
daggerCompiler = "com.google.dagger:dagger-compiler:_"
epoxy = "com.airbnb.android:epoxy:_"
epoxyProcessor = "com.airbnb.android:epoxy-processor:_"
hilt = "com.google.dagger:hilt-android:_"
hiltCompiler = "com.google.dagger:hilt-android-compiler:_"
hiltTesting = "com.google.dagger:hilt-android-testing:_"
hiltGradle = "com.google.dagger:hilt-android-gradle-plugin:_"
lifecycle = "androidx.lifecycle:lifecycle-compiler:_"
roomCompiler = "androidx.room:room-compiler:_"
activity = "androidx.activity:activity:_"
activityCompose = "androidx.activity:activity-compose:_"
appcompat = "androidx.appcompat:appcompat:_"
cardview = "androidx.cardview:cardview:_"
constraintlayout = "androidx.constraintlayout:constraintlayout:_"
coordinatorLayout = "androidx.coordinatorlayout:coordinatorlayout:_"
coreKtx = "androidx.core:core-ktx:_"
composeCompiler = "androidx.compose.compiler:compiler:_"
composeUi = "androidx.compose.ui:ui:_"
composeFoundation = "androidx.compose.foundation:foundation:_"
composeMaterial = "androidx.compose.material:material:_"
composeTest = "androidx.compose.ui:ui-test-junit4:_"
composeUiTestManifest = "androidx.compose.ui:ui-test-manifest:_"
detektFormatting = "io.gitlab.arturbosch.detekt:detekt-formatting:_"
espressoIdlingResource = "androidx.test.espresso:espresso-idling-resource:_"
fragment = "androidx.fragment:fragment:_"
fragmentKtx = "androidx.fragment:fragment-ktx:_"
fragmentTesting = "androidx.fragment:fragment-testing:_"
koin = "io.insert-koin:koin-android:_"
kotlinGradle = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"
kotlin = "org.jetbrains.kotlin:kotlin-stdlib:_"
kotlinCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"
kotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:_"
lifecycleCommon = "androidx.lifecycle:lifecycle-common-java8:_"
lifecycleTest = "androidx.lifecycle:lifecycle-runtime-testing:_"
lottie = "com.airbnb.android:lottie:_"
moshi = "com.squareup.moshi:moshi:_"
moshiCodegen = "com.squareup.moshi:moshi-kotlin-codegen:_"
moshiKotlin = "com.squareup.moshi:moshi-kotlin:_"
multidex = "androidx.multidex:multidex:_"
navigationFragmentKtx = "androidx.navigation:navigation-fragment-ktx:_"
navigationUiKtx = "androidx.navigation:navigation-ui-ktx:_"
navigationCompose = "androidx.navigation:navigation-compose:_"
picasso = "com.squareup.picasso:picasso:_"
recyclerview = "androidx.recyclerview:recyclerview:_"
retrofit = "com.squareup.retrofit2:retrofit:_"
retrofitMoshi = "com.squareup.retrofit2:converter-moshi:_"
retrofitRxJava = "com.squareup.retrofit2:adapter-rxjava2:_"
roomRuntime = "androidx.room:room-runtime:_"
roomRxJava = "androidx.room:room-rxjava2:_"
runtimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:_"
runtimeCompose = "androidx.lifecycle:lifecycle-runtime-compose:_"
rxAndroid = "io.reactivex.rxjava2:rxandroid:_"
rxJava = "io.reactivex.rxjava2:rxjava:_"
viewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:_"
viewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:_"
viewModelSavedState = "androidx.lifecycle:lifecycle-viewmodel-savedstate:_"
core = "androidx.test:core:_"
espresso = "androidx.test.espresso:espresso-core:_"
junit = "junit:junit:_"
junitExt = "androidx.test.ext:junit:_"
junit5 = "org.junit.jupiter:junit-jupiter:_"
kotlinCoroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"
mockito = "org.mockito:mockito-core:_"
mockitoKotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:_"
mockk = "io.mockk:mockk:_"
roboeletric = "org.robolectric:robolectric:_"
mavenPublishGradle = "com.vanniktech:gradle-maven-publish-plugin:_"
dokkaGradle = "org.jetbrains.dokka:dokka-gradle-plugin:_"
